definitions:
  response.ClientPublishData:
    properties:
      client_id:
        description: 客户端id
        type: string
      index:
        description: 消息索引 提交消息时自增
        type: integer
      message:
        description: 消息数据 json字符串
        type: string
    type: object
  response.GroupPublishData:
    properties:
      group_id:
        description: 消息组
        type: string
      index:
        description: 消息索引 提交消息时自增
        type: integer
      message:
        description: 消息数据 json字符串
        type: string
    type: object
  response.StandardResponse:
    properties:
      code:
        description: 0 成功 1失败
        type: integer
      data: {}
      message:
        description: 提示语
        type: string
    type: object
  response.UserPublishData:
    properties:
      index:
        description: 消息索引 提交消息时自增
        type: integer
      message:
        description: 消息数据 json字符串
        type: string
      user_id:
        description: 用户id
        type: string
    type: object
  wsInner.publishResponse:
    properties:
      index:
        description: 消息索引
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/inner/ws-gateway-service/client-publish:
    post:
      parameters:
      - description: 推送消息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.ClientPublishData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.StandardResponse'
            - properties:
                data:
                  $ref: '#/definitions/wsInner.publishResponse'
              type: object
      summary: 推送链接消息
      tags:
      - 推送消息-内部
  /api/inner/ws-gateway-service/group-publish:
    post:
      parameters:
      - description: 推送消息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.GroupPublishData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.StandardResponse'
            - properties:
                data:
                  $ref: '#/definitions/wsInner.publishResponse'
              type: object
      summary: 推送组消息
      tags:
      - 推送消息-内部
  /api/inner/ws-gateway-service/user-publish:
    post:
      parameters:
      - description: 推送消息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.UserPublishData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.StandardResponse'
            - properties:
                data:
                  $ref: '#/definitions/wsInner.publishResponse'
              type: object
      summary: 推送用户消息
      tags:
      - 推送消息-内部
  /api/public/ws-gateway-service/group/msg/index:
    get:
      parameters:
      - in: query
        name: group_id
        type: string
      - in: query
        name: index
        required: true
        type: integer
      - in: query
        name: user_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.StandardResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.GroupPublishData'
              type: object
      summary: 组消息
      tags:
      - 组消息-外部
  /api/public/ws-gateway-service/user/msg/index:
    get:
      parameters:
      - in: query
        name: group_id
        type: string
      - in: query
        name: index
        required: true
        type: integer
      - in: query
        name: user_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.StandardResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.UserPublishData'
              type: object
      summary: 组消息
      tags:
      - 组消息-外部
swagger: "2.0"
